### ISSUE TITLE
请明显的注明此项目与 Vue Mini 的关系

### ISSUE THREAD

**Issue by yangmingshan** [JasKang/rubic#25]
Hi，你好。我是 [Vue Mini](https://github.com/vue-mini/vue-mini) 的作者。如果我没搞错的话，这个项目应该是 Fork 至 Vue Mini 吧。Vue Mini 当然是欢迎 Fork 的，但是我只看到你在文档简介提了一下 Vue Mini，我的 Commits 一个都不剩。这样干怕是不太道义，而且也违反 MIT 开源协议。

所以请在 README 以及文档首页明显的地方注明此项目与 Vue Mini 的关系。

**Comment by JasKang** [comment]
> 我的 Commits 一个都不剩。这样干怕是不太道义，而且也违反 MIT 开源协议。

回应一下

文档部分有挺多是 copy 的 `vue` 和 ` Vue Mini`（这部分会重点注明）。至于项目代码，并没有 fork Vue Mini ，所以没有你的 commits 是正常的。

这个项目是在公司内项目，github 的版本是经过脱敏后的，所以也没有保留之前的 commit 。2021 年 4 月份开始的第一个 commit ， 那时候我们还没有用 @vue/reactivity ，也根本不知道  `Vue Mini` 。

<img width="1366" alt="image" src="https://github.com/user-attachments/assets/e85b71bb-1a40-4f0e-849a-4c16272c8188">

事实上我们更多是受到了 [miniprogram-composition-api](https://github.com/clevok/miniprogram-composition-api) 的启发。


刚看到你说`一模一样`，在我看来仅有 `@vue/reactivity` 部分是一样的。而其他理念是完全不一样的。如：

- setup：`rubic` 中统一使用 attached 使 component 和 page setup 执行时机保持一致，需要从 props 声明 query 参数， `Vue Mini` 使用 onLoad 可以方便拿到参数。
- 依赖注入： `Vue Mini` 中有 依赖注入，而 `rubic`  因为小程序无法获取父级实例所以并未提供相应能力
- 插件能力：`rubic` 提供了插件能力来帮助全局公共能力。

我司是小程序比重非常大，所以该框架一直在迭代，只是并没有同步到 github。我刚看了下 `Vue Mini` 的提交，中间有一年多都没有任何更新，之前的更新也都仅仅是更新 @vue/reactivity ，似乎并没有在小程序端做什么, 比如最更新了 flush: 'post'  而这个我们两年前就做了。 

不可否认 `@vue/reactivity` 和 `组合式 api ` 是一样的，而这是 vue 的概念，并不是 `Vue Mini` 特有的。 所以我不明白你为何有如下说法

> Rubic 是 Fork 的 Vue Mini，你还是换成 Vue Mini 吧

别人问你区别，而你并不知道区别就直接推荐用 `Vue Mini`。

然后还关注到你在 vueconf 分享了 `Vue Mini`,  恭喜。 如果你觉得这个项目在这里影响到推广 `Vue Mini` 或者提升自身影响力了，请尝试把  `Vue Mini` 做得更好。

**Comment by yangmingshan** [comment]
我又看了一遍 `Rubic` 的代码，与 `Vue Mini` 的相似程度让我实在很难相信这是一个巧合，或者严谨点说这个可能性几乎为零。我也看了 `miniprogram-composition-api` 的代码，人家的代码跟 `Vue Mini` 可一点也不像。

反正 `Vue Mini` 是全程在 GitHub 上公开开发的，每一个 Commit 都可以在 GitHub 上找到，每一处代码都可以找到对应的进化路径跟前后的细节调整。我相信我能找到坚实的证据。你说这是公司内部项目，要证明你的说法也很简单，把 Commits 全部公开出来就可以了，这种框架代码我不觉得有多少敏感信息。就算真的有敏感信息无法公开，我相信你们公司不止你一个人吧，可以找同事出来证实一下，同事应该很乐意吧。说过最终证明是我误会了，我愿意公开道歉。

> 依赖注入： `Vue Mini` 中有 依赖注入，而 `rubic` 因为小程序无法获取父级实例所以并未提供相应能力

你的第一个 Commit 里面可是有 `inject.ts` 这个文件的哟，测试文件 `inject.spec.ts` 也有哟，你要不要去看一下它们跟 `Vue Mini` 的相似度啊？不必尝试毁灭证据，我已经 Fork 了你的仓库。

> Rubic 是 Fork 的 Vue Mini，你还是换成 Vue Mini 吧

我还是很谨慎用的 `Fork` 这个词，刻意没用更严厉的词汇，比如**抄袭**。

我原本只是觉得你的做法很没品，也可能是新人不懂规则图一时好玩，加个声明这事儿就算了，`Rubic` 也根本没能力影响 `Vue Mini`。你的这个回应只能证明你是纯纯的坏了。现在这事儿就不是加个声明能了结的了。

你现在真诚的道歉还来得及。

**Comment by akinoccc** [comment]
话说一个公司的内部框架允许发布到个人账号？

**Comment by yangmingshan** [comment]
为了方便吃瓜群众们吃瓜。

@JasKang 声称 `Rubic` 没用做依赖注入，可是初始提交里面确有依赖注入的代码，连测试代码都有，还跟 `Vue Mini` 一模一样，下面是对比链接：

## inject.ts

`Rubic` 的初始提交：
https://github.com/JasKang/rubic/commit/5b141a187b2e4e1ab59fff1dbd7853eac59bbc1e#diff-fea34f0968e2cf9b37aaf0eb78d6240ccf0f7e1e6a67b99bd4b828bb36ac6d07

`Vue Mini` 的源码：
https://github.com/vue-mini/vue-mini/blob/master/packages/core/src/inject.ts

`Vue` 的源码：
https://github.com/vuejs/core/blob/main/packages/runtime-core/src/apiInject.ts

## inject.spec.ts

`Rubic` 的初始提交：
https://github.com/JasKang/rubic/commit/5b141a187b2e4e1ab59fff1dbd7853eac59bbc1e#diff-8038ba757e8c66965a847c4b6f0d93280a273270322e9ed2d4e8a5300ac5fb9e

`Vue Mini` 的源码：
https://github.com/vue-mini/vue-mini/blob/master/packages/core/__tests__/inject.spec.ts

`Vue` 的源码：
https://github.com/vuejs/core/blob/main/packages/runtime-core/__tests__/apiInject.spec.ts

@JasKang 你有什么要说的吗？

**Comment by JasKang** [comment]
> 要证明你的说法也很简单，把 Commits 全部公开出来就可以了，这种框架代码我不觉得有多少敏感信息。

我不再做任何回应，你请便

**Comment by yangmingshan** [comment]
@JasKang 你要这样死猪不怕开水烫的话，我只能向 GitHub 举报，并向你的公司反映了。
