### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by fudx** [JasKang/rubic#5]
问一下，未来支持多端吗

**Comment by JasKang** [comment]
> 问一下，未来支持多端吗

现在这种模式下其实和 Vue3 是非常相似的，可以整个编译工具替换成 Vue3 以支持 web 端。

不过目前来说还有点远，当下的精力主要还是在小程序这块

**Comment by aboutZZ** [comment]
目前0.1版本稳定不？能否放在生产中

**Comment by JasKang** [comment]
> 目前0.1版本稳定不？能否放在生产中

之前已经有很多内部项目使用一年多了（内部版本更多业务藕合）。

但这个开源的版本是经过了调整的，还没有经过大规模的生产使用。不过我们的单元测试是齐全的，目前也有一些项目正开始使用了。
