### ISSUE TITLE
问个问题 项目起不来

### ISSUE THREAD

**Issue by fudx** [JasKang/rubic#6]
(node:29741) UnhandledPromiseRejectionWarning: file:///Users/dxm/Desktop/%E5%AD%A6%E4%B9%A0/rubic/node_modules/vitepress/dist/node/serve-1b26f7f9.js:1
import { setDefaultResultOrder } from 'node:dns';
         ^^^^^^^^^^^^^^^^^^^^^
SyntaxError: The requested module 'node:dns' does not provide an export named 'setDefaultResultOrder'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:98:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:143:5)
    at async Loader.import (internal/modules/esm/loader.js:165:24)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:29741) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:29741) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

这个问题咋弄

**Comment by JasKang** [comment]
node 版本的问题，vitepress 需要较高版本的 Node 16

https://github.com/vuejs/vitepress/issues/1384
